import Navbar from "@/components/Navigation/Navbar";
import FooterSection from "@/components/section/FooterSection";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed self-center z-50 flex justify-center w-full">
        <Navbar/>
        </div>
        {children}
      <FooterSection/>
      </body>
    
    </html>
  );
}
